# Generated by Django 4.0.3 on 2022-04-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sousmotapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='dictionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sousmotapp.dictionary'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sousmotapp.mode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='nb_letters',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='nb_words',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_s',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
