name: Deploy to our prod !

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known host
        run: |
          ssh-keyscan -p ${{ secrets.DEPLOY_HOST_SSH_PORT }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy
        env:
          SOUSMOT_HOST: ${{ secrets.SOUSMOT_HOST }}
          SOUSMOT_USER: ${{ secrets.SOUSMOT_USER }}
          SOUSMOT_PORT: ${{ secrets.SOUSMOT_PORT }}
        run: |
          bundle exec cap production deploy
